### ISSUE TITLE
Full Windows Support Needed

### ISSUE THREAD

**Issue by Bardia323** [shog-ai/shoggoth#2]
## Issue
Windows compatibility is incomplete.

## Goal
Achieve full functionality on Windows OS.

## Tasks
- [ ] Test current build on Windows
- [ ] Identify non-working features
- [ ] Fix compatibility issues
- [ ] Document Windows-specific instructions

## Environment
- Windows version: Windows 10

**Comment by wbic16** [comment]
FYI for anyone waiting for Windows compatibility - you can easily build/run shog from Ubuntu using WSL.

**Comment by thenetrunna** [comment]
fixed by v1.0.2
